#!/usr/bin/python
#
# Copyright 2014 TWO SIGMA OPEN SOURCE, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import subprocess
import time
import urllib2
import signal

# make sure everything is properly installed
os.system("rm -rf ./node_modules/*")
os.system("npm install")
os.system("node_modules/protractor/bin/webdriver-manager update");

with open(os.devnull, "w") as fnull:
    webcontrol = subprocess.Popen(["node_modules/protractor/bin/webdriver-manager", "start"], stdout=fnull, stderr=fnull, preexec_fn=os.setsid);

beaker = subprocess.Popen(["../core/beaker.command", "-open-browser", "false"], stdout=subprocess.PIPE, preexec_fn=os.setsid)

for line in iter(beaker.stdout.readline, ''):
    print(">>>" + line.strip())
    if line.startswith('Beaker listening on'):
        break

result = os.system("./node_modules/protractor/bin/protractor protractorConf.js");
result2 = 1
if not result:
    result2 = os.system("./node_modules/protractor/bin/protractor protractorWithoutRestartBrowserConf.js");
if not result2:
    result2 = os.system("./node_modules/protractor/bin/protractor protractorOneInstanceConf.js");

# Skipping memory tests because they hang on Jenkins
# os.system("node memory-tests.js")

# Send the signal to all the process groups
os.killpg(os.getpgid(beaker.pid), signal.SIGTERM)
os.killpg(os.getpgid(webcontrol.pid), signal.SIGTERM)

if result2:
    sys.exit(20)
