import IHihglighterState from "./IHighlighterState";
export default interface IDataModelState {
    alignmentForColumn?: {};
    alignmentForType?: {};
    cellHighlighters: IHihglighterState[];
    columnNames: string[];
    columnOrder: string[];
    columnsFrozen?: {};
    columnsFrozenRight?: {};
    columnsVisible: {};
    contextMenuItems?: string[];
    contextMenuTags?: {};
    dataFontSize?: number | null;
    doubleClickTag?: string | null;
    fontColor?: string[];
    hasDoubleClickAction?: boolean;
    hasIndex: boolean;
    headerFontSize?: number | null;
    headersVertical?: boolean;
    rendererForColumn?: {};
    rendererForType?: {};
    stringFormatForColumn: {};
    stringFormatForTimes?: string | null;
    stringFormatForType?: {};
    subtype?: string;
    timeZone?: string;
    timeStrings?: any;
    tooManyRows?: boolean;
    tooltips: string[][];
    type?: string;
    types: string[];
    values: any;
}
