import { Reducer } from "@phosphor/datastore";
import IDataModelState from "../interface/IDataGridModelState";
export declare const UPDATE_MODEL_DATA = "UPDATE_MODEL_DATA";
export declare const UPDATE_COLUMN_RENDERER = "UPDATE_COLUMN_RENDERER";
export declare const UPDATE_COLUMN_ORDER = "UPDATE_COLUMN_ORDER";
export declare const UPDATE_COLUMN_FROZEN = "UPDATE_COLUMN_FROZEN";
export declare const UPDATE_COLUMN_VISIBLE = "UPDATE_COLUMN_VISIBLE";
export declare const UPDATE_COLUMNS_VISIBLE = "UPDATE_COLUMNS_VISIBLE";
export declare const RESET_COLUMNS_ORDER = "RESET_COLUMNS_ORDER";
export declare const ADD_COLUMN_HIGHLIGHTER = "ADD_COLUMN_HIGHLIGHTER";
export declare const REMOVE_COLUMN_HIGHLIGHTER = "REMOVE_COLUMN_HIGHLIGHTER";
declare const dataGridModelReducer: Reducer<IDataModelState>;
export default dataGridModelReducer;
