import { Reducer } from "@phosphor/datastore";
import { IColumnsState } from "../interface/IColumn";
export declare const UPDATE_COLUMNS_STATES = "UPDATE_COLUMNS_STATES";
export declare const UPDATE_COLUMN_STATE = "UPDATE_COLUMNS_STATE";
export declare const UPDATE_COLUMN_POSITIONS = "UPDATE_COLUMN_POSITIONS";
export declare const UPDATE_COLUMNS_TYPES = "UPDATE_COLUMNS_TYPES";
export declare const UPDATE_COLUMNS_NAMES = "UPDATE_COLUMNS_NAMES";
export declare const UPDATE_COLUMNS_FILTERS = "UPDATE_COLUMNS_FILTERS";
export declare const UPDATE_COLUMN_FILTER = "UPDATE_COLUMN_FILTER";
export declare const UPDATE_COLUMN_HORIZONTAL_ALIGNMENT = "UPDATE_COLUMN_HORIZONTAL_ALIGNMENT";
export declare const UPDATE_COLUMN_FORMAT_FOR_TIMES = "UPDATE_COLUMN_FORMAT_FOR_TIMES";
export declare const UPDATE_COLUMN_DISPLAY_TYPE = "UPDATE_COLUMN_DISPLAY_TYPE";
export declare const UPDATE_COLUMN_SORT_ORDER = "UPDATE_COLUMN_SORT_ORDER";
export declare const UPDATE_COLUMN_WIDTH = "UPDATE_COLUMN_WIDTH";
declare const columnReducer: Reducer<IColumnsState>;
export default columnReducer;
