import { CellRenderer } from "@phosphor/datagrid";
import { IColumnState } from "./interface/IColumn";
import { BeakerXDataStore } from "./store/BeakerXDataStore";
export declare const DEFAULT_TIME_FORMAT = "YYYYMMDD HH:mm:ss.SSS ZZ";
export declare class DataFormatter {
    store: BeakerXDataStore;
    constructor(store: BeakerXDataStore);
    destroy(): void;
    readonly stringFormatForColumn: {};
    readonly timeStrings: any;
    readonly timeZone: string;
    readonly stringFormatForType: {};
    readonly formatForTimes: any;
    readonly columnNames: string[];
    getFormatFnByDisplayType(displayType: any, columnState?: IColumnState): CellRenderer.ConfigFunc<string>;
    private isNull;
    private handleNull;
    private rawValue;
    private value;
    private string;
    private integer;
    private formattedInteger;
    private double;
    private doubleWithPrecision;
    private exponential_5;
    private exponential_15;
    private datetime;
    private getTimeFormatForColumn;
    private datetimeWithFormat;
    private boolean;
    private html;
}
