#!/usr/bin/python
#
# Copyright 2015 TWO SIGMA OPEN SOURCE, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import shutil
import errno

zip_name = sys.argv[1]
core = '../../core/'
if os.path.exists(zip_name):
    shutil.rmtree(zip_name)
if os.path.exists(zip_name + '.zip'):
    os.remove(zip_name + '.zip')
os.mkdir(zip_name)
if sys.platform == 'darwin' or sys.platform == 'linux2':
    contents = ['config', 'src/main/web', 'build/install/core', 'nginx', 'LICENSE', 'beaker.command']
    for f in contents:
        path = f.split('/')
        if len(path) > 1:
            os.makedirs(zip_name + '/' + '/'.join(path[:-1]))
        link = f
        try:
            shutil.copytree(core + link, zip_name + '/' + f)
        except OSError as exc:
            if exc.errno == errno.ENOTDIR:
                shutil.copy2(core + link, zip_name + '/' + f)
            else: raise

        #os.copy(link, zip_name + '/' + f)
