#!/bin/sh
rm -rf BeakerOSX
mkdir BeakerOSX
mv Beaker.app BeakerOSX/Beaker.app
./create-dmg/create-dmg \
--volname "Beaker" \
--window-pos 200 120 \
--window-size 800 400 \
--icon-size 100 \
--icon Beaker.app 200 190 \
--hide-extension Beaker.app \
--app-drop-link 600 185 \
Beaker.dmg \
BeakerOSX/
