#!/bin/bash
#
# Copyright 2014 TWO SIGMA INVESTMENTS, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BEAKER_JULIA=ipython

while [ -n "$1" ]
do
    case "$1" in
        --path*) BEAKER_JULIA="${1#??????}"; shift;;
        *) break;;
    esac
done

exec $BEAKER_JULIA notebook --profile julia --pylab inline --IPKernelApp.pyloab='inline' --NotebookApp.ip=127.0.0.1 --NotebookApp.port=$1 --NotebookApp.open_browser=False
