/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twosigma_beaker_cpp_utils_CppEvaluator */

#ifndef _Included_com_twosigma_beaker_cpp_utils_CppEvaluator
#define _Included_com_twosigma_beaker_cpp_utils_CppEvaluator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twosigma_beaker_cpp_utils_CppEvaluator
 * Method:    cLoadAndRun
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_twosigma_beaker_cpp_utils_CppEvaluator_cLoadAndRun
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_twosigma_beaker_cpp_utils_CppEvaluator_jobDescriptor */

#ifndef _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_jobDescriptor
#define _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_jobDescriptor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread */

#ifndef _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread
#define _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MIN_PRIORITY
#define com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MIN_PRIORITY 1L
#undef com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_NORM_PRIORITY
#define com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_NORM_PRIORITY 5L
#undef com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MAX_PRIORITY
#define com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MyRunnable */

#ifndef _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MyRunnable
#define _Included_com_twosigma_beaker_cpp_utils_CppEvaluator_workerThread_MyRunnable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
